### ISSUE TITLE
Npm Package install issue

### ISSUE THREAD

**Issue by jonshern** [tmobile/pacbot#27]
When executing this command on amazon linux 2
```bash
sudo yum -y install java-1.8.0-openjdk npm docker maven wget unzip mysql
```

I get this returned
```
No package npm available.
```

When i run npm i get not found.

**Comment by jonshern** [comment]
Looks like you are installing when you build the app 
[INFO] Installing node version v8.12.0
[INFO] Creating temporary directory /home/ec2-user/pacbot/webapp/node_tmp
[INFO] Downloading Node.js from http://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.gz to /home/ec2-user/pacbot/webapp/node_tmp/node.tar.gz
[INFO] No proxy was configured, downloading directly
[INFO] Extracting Node.js files in node_tmp
[INFO] Unpacking /home/ec2-user/pacbot/webapp/node_tmp/node.tar.gz into /home/ec2-user/pacbot/webapp/node_tmp
[INFO] Moving node binary to /home/ec2-user/pacbot/webapp/node/node
[INFO] Deleting temporary directory /home/ec2-user/pacbot/webapp/node_tmp
[INFO] Installed node locally.
[INFO] Installing npm version 6.4.1
[INFO] Downloading NPM from http://registry.npmjs.org/npm/-/npm-6.4.1.tgz to /home/ec2-user/pacbot/webapp/npm.tar.gz
[INFO] No proxy was configured, downloading directly
[INFO] Extracting NPM files in node/
[INFO] Unpacking /home/ec2-user/pacbot/webapp/npm.tar.gz into /home/ec2-user/pacbot/webapp/node
[INFO] Installed NPM locally.

**Comment by bobrich** [comment]
Fellow tinkerer here.  Are you seeing errors of this nature shortly after the node/npm install in the install log?

`[ERROR] Unable to save binary /tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/node-sass/vendor'
[ERROR]     at Object.fs.mkdirSync (fs.js:885:18)
[ERROR]     at sync (/tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/mkdirp/index.js:71:13)
[ERROR]     at Function.sync (/tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/mkdirp/index.js:77:24)
[ERROR]     at checkAndDownloadBinary (/tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/node-sass/scripts/install.js:114:11)
[ERROR]     at Object.<anonymous> (/tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/node-sass/scripts/install.js:157:1)
[ERROR]     at Module._compile (module.js:653:30)
[ERROR]     at Object.Module._extensions..js (module.js:664:10)
[ERROR]     at Module.load (module.js:566:32)
[ERROR]     at tryModuleLoad (module.js:506:12)
[ERROR]     at Function.Module._load (module.js:498:3)
[ERROR]   errno: -13,
[ERROR]   code: 'EACCES',
[ERROR]   syscall: 'mkdir',
[ERROR]   path: '/tmp/pacman_cloned_dir_1541296600.25/webapp/node_modules/node-sass/vendor' }
`

I'm getting errors when running the application and it looks like a good portion of the API code has not been deployed (e.g. 404 errors when posting to /api/compliance).  I'm wondering if it's related to this or not.  It appears to be due to some kind of permissions issue with node

I'm running on Amazon Linux 2, using this to install my prerequisites:

`sudo yum update -y
sudo yum install -y docker maven python-pip mysql wget unzip java-1.8.0-openjdk epel-release git

wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
unzip terraform_0.11.10_linux_amd64.zip
sudo mv terraform /usr/bin
rm terraform_0.11.10_linux_amd64.zip

git clone https://github.com/tmobile/pacbot.git
cd pacbot/installer
pip install --user -r requirements.txt

sudo service docker start`

**Comment by johnakash** [comment]
@bobrich , Could you please pull the latest installer and give a try again? We are recommending CentOS / RHEL for installing PacBot.

**Comment by johnakash** [comment]
@jonshern / @bobrich , This issue is fixed in our latest release. Please pull latest installer and give a shot.
