### ISSUE TITLE
ECS services are not running

### ISSUE THREAD

**Issue by aparnam93** [tmobile/pacbot#343]
ECS services are not running , I have specified one public and one private subnet in the same order . What can be the issue . how to debug this ?

**Comment by sajeer-nooh** [comment]
Could you please check the cloudwatch logs. 

**Steps**
1. Go to cloudwatch logs
2. Click on pacbot/apis
3. Click on the log files and check if there is any error or not

Usually this should not happen but if you are enabled ALB as internet-facing, then you should follow the below steps.

1. All subnets associated with ALB should be public. If you have provided private and public subnets during install, then you have to manually change the subnets of ALB
2. Check the security groups so that the incoming hits(inbound) are allowed from the containers. You can take the eip and add them or select the IPs of containers and add them.
  You can troubleshoot this by enabling incoming hits from anywhere and check if the app is working or not. If it is working then remove the inbound rule ad add specific IP address of containers.

**Comment by aparnam93** [comment]
But in the ECS services the tasks are not running

**Comment by sajeer-nooh** [comment]
@aparnam93 , are you mentioning about pacbot_Batch cluster? You do not need to worry about that. AWS Batch job automatically add services when rules get tirggered

**Comment by sajeer-nooh** [comment]
Can you check the cloudwatch log for the reason
1. Go to failed job click on it
2. At the bottom of the job details, you can see log link
3. Click on it and go to the cloudwatch 
4. Click on text format
5. Check the reason for failure

**Comment by aparnam93** [comment]
Im not able to redirect to the logs from the console . is it the permission issue?

**Comment by sajeer-nooh** [comment]
@aparnam93 
I hope, you have successfully installed PacBot. Please do let me know if you are still facing issues in the installation.

**Comment by santhoshigorle** [comment]
@aparnam93 - Hope, your issue resolved. Feel  free to reopen issue if the issue persists.
