### ISSUE TITLE
Issues with IAM permissions

### ISSUE THREAD

**Issue by jdbeitz** [tmobile/pacbot#8]
Upon trying to deploy, i have created an iam user with full admin access, generated keys, and started the install.  I continuously receive:
     Nececssary permissions are NOT avaiable!!!
the pacman-install.log logs only:
     "Starting pacman installation"

**Comment by sbkg0002** [comment]
How did you fix this?

**Comment by hawkesnc** [comment]
I have been running into this issue as well. There is something fundamentally wrong with the logic on checking the  IAM permissions: https://github.com/tmobile/pacbot/blob/master/installer/jsonRead.py#L297

It is using a "count" of the policies here: https://github.com/tmobile/pacbot/blob/master/installer/resource.json#L7-L22
rather than actually checking to see if those permissions exist.

If you create a user with FULL admin access, when the error appears, force it to continue by responding "Yes" (capital Y) to the question that comes after: 
`If you have added custom policies with all permissions, please type Yes or No: Yes`

Although this may work, the rest of the installer seems pretty buggy

**Comment by bobrich** [comment]
For anyone running into this, the install then prompts to ask the user if they built a custom policy providing the permissions.  Just answer 'Yes' and the install will continue.

**Comment by jakauppila** [comment]
Ran into this as well. Just granted the IAM user full Admin and it said necessary permissions are not available.
